const DEFAULT_QUERY_FILMS_LIMIT = 10;
const DEFAULT_QUERY_FILMS_OFFSET = 0;
const DEFAULT_QUERY_CATEGORIES_LIMIT = 20;
const DEFAULT_QUERY_CATEGORIES_OFFSET = 0;

module.exports = {
  DEFAULT_QUERY_FILMS_LIMIT,
  DEFAULT_QUERY_FILMS_OFFSET,
  DEFAULT_QUERY_CATEGORIES_LIMIT,
  DEFAULT_QUERY_CATEGORIES_OFFSET,
}